name: speedmaths_pro
description: "Boost your mental math speed with daily practice, streaks, and challenges."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1

  # State management
  provider: ^6.1.0

  # Local storage
  shared_preferences: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # UI / Utils
  flutter_screenutil: ^5.6.0
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  simple_heatmap_calendar: ^0.0.3
  font_awesome_flutter: ^10.7.0
  fl_chart: ^1.1.1
  animate_do: ^3.3.4
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  animations: ^2.0.0
  share_plus: ^10.0.2
  connectivity_plus: ^5.0.2
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lints
  flutter_lints: ^5.0.0
  # Code generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  # ðŸš€ Integration testing
  integration_test:
    sdk: flutter

  

flutter:
  uses-material-design: true

  assets:
    - assets/images/elf_icon.png
    - assets/images/google_logo.png
